server:
  port: 10010
dubbo:
  application:
    name: yitao-seller-webapi
  protocol:
    port: 4000
  registry:
    address: zookeeper://192.168.91.131:2181
  provider:
    timeout: 60000
  consumer:
    timeout: 60000
