server:
  port: 7781
dubbo:
  application:
    name: yitao-auth-service
  registry:
    address: zookeeper://192.168.91.131:2181
  protocol:
    port: 20885
yt:
  jwt:
    secret: yt@Login(Auth}*^778)&gerry%f35YUE2
    pubKeyPath: D:/vip/keys/id_rsa.pub
    priKeyPath: D:/vip/keys/id_rsa.pri
    expire: 30
    cookieName: YT_TOKEN
    cookieMaxAge: 1800

api:
  url: http://api.yitao.com/