server:
  port: 7777

dubbo:
  application:
    name: yitao-upload-service
  registry:
    address: zookeeper://192.168.221.99:2181
  pprotocol:
    port: 20881
    payload: 104857600
    name: hessian


yitao:
  upload:
    configPath: classpath:fastdfs/fdfs_client.conf
    baseUrl: http://yitao.image.com/
