spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    password: 1111
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/orange?useSSL=false&serverTimezone=UTC
    username: root

server:
  port: 7779
dubbo:
  application:
    name: yitao-user-service
  registry:
    address: zookeeper://192.168.91.131:2181
  protocol:
    port: 20886

logging:
  level:
    com.yitao.mapper: debug
