server:
  port: 10020

dubbo:
  application:
    name: yitao-upload-webapi
  registry:
    address: zookeeper://192.168.221.99:2181
  protocol:
    name: hession

spring:
  servlet:
    multipart:
      max-file-size: 100MB
