spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    password: 1111
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/orange?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
  rabbitmq:
    addresses: 192.168.91.131
    username: admin
    password: admin
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: yt.item.exchange
    publisher-confirms: true

dubbo:
  application:
    name: yitao-seller-service
  protocol:
    port: 3000
  registry:
    address: zookeeper://192.168.91.131:2181
  provider:
    timeout: 60000
  consumer:
    timeout: 60000

logging:
  level:
    com.yitao.mapper: debug

server:
  port: 8000

